---
swagger: "2.0"
info:
  description: "Adroid chat application REST API documentation"
  version: "1.0.0"
  title: "Mobilszoftver labor (VIAUMB02)"
  contact:
    name: "Leonard László"
    email: "laslaul@yahoo.com"
  license:
    name: "GPL-3.0"
    url: "https://opensource.org/licenses/GPL-3.0"
host: "laslaul.ddns.net:8080"
basePath: "/api"
schemes:
- "http"
- "https"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /conversations:
    get:
      tags:
      - "conversations"
      summary: "Gets user's conversations"
      operationId: "getConversations"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "List of conversations"
          schema:
            $ref: "#/definitions/ListOfConversations"
        400:
          description: "Bad request"
          schema:
            $ref: "#/definitions/APIMessage"
        401:
          description: "Unauthorized"
          schema:
            $ref: "#/definitions/APIMessage"
      security:
      - basicAuth: []
      x-swagger-router-controller: "Conversations"
    post:
      tags:
      - "conversations"
      summary: "Creates new conversation for user"
      operationId: "createConversation"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "conversation"
        required: true
        schema:
          $ref: "#/definitions/Conversation"
      responses:
        201:
          description: "Created"
          schema:
            $ref: "#/definitions/APIMessage"
        400:
          description: "Bad request"
          schema:
            $ref: "#/definitions/APIMessage"
        401:
          description: "Unauthorized"
          schema:
            $ref: "#/definitions/APIMessage"
      security:
      - basicAuth: []
      x-swagger-router-controller: "Conversations"
  /login:
    get:
      tags:
      - "login"
      summary: "Confirms user that his credentials are accepted by server."
      operationId: "loginUser"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "Authorized"
          schema:
            $ref: "#/definitions/APIMessage"
        400:
          description: "Bad request"
          schema:
            $ref: "#/definitions/APIMessage"
        401:
          description: "Unauthorized"
          schema:
            $ref: "#/definitions/APIMessage"
      security:
      - basicAuth: []
      x-swagger-router-controller: "Login"
  /messages/{partner}:
    get:
      tags:
      - "messages"
      summary: "Gets a list of messages in a conversation"
      operationId: "getMessages"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "partner"
        required: true
        type: string
      responses:
        200:
          description: "List of messages in a conversation"
          schema:
            $ref: "#/definitions/ListOfMessages"
        400:
          description: "Bad request"
          schema:
            $ref: "#/definitions/APIMessage"
        401:
          description: "Unauthorized"
          schema:
            $ref: "#/definitions/APIMessage"
      security:
      - basicAuth: []
      x-swagger-router-controller: "Messages"
  /messages:
    post:
      tags:
      - "messages"
      summary: "Sends a new message to a user"
      operationId: "sendMessage"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "message"
        required: true
        schema:
          $ref: "#/definitions/NewMessage"
      responses:
        201:
          description: "Created"
          schema:
            $ref: "#/definitions/APIMessage"
        400:
          description: "Bad request"
          schema:
            $ref: "#/definitions/APIMessage"
        401:
          description: "Unauthorized"
          schema:
            $ref: "#/definitions/APIMessage"
      security:
      - basicAuth: []
      x-swagger-router-controller: "Messages"
  /register:
    post:
      tags:
      - "registration"
      summary: "Registers a new user"
      operationId: "registerUser"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "User"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        201:
          description: "Created"
          schema:
            $ref: "#/definitions/APIMessage"
        400:
          description: "Bad request"
          schema:
            $ref: "#/definitions/APIMessage"
      x-swagger-router-controller: "Registration"
securityDefinitions:
  basicAuth:
    description: "HTTP Basic Authentication. Works over `HTTP` and `HTTPS`"
    type: "basic"
definitions:
  NewMessage:
    type: "object"
    required:
    - "message"
    - "receiver"
    properties:
      receiver:
        type: "string"
      message:
        type: "string"
  Message:
    type: "object"
    required:
    - "message"
    - "receiver"
    - "sender"
    properties:
      sender:
        type: "string"
      receiver:
        type: "string"
      message:
        type: "string"
  APIMessage:
    type: "object"
    required:
    - "message"
    properties:
      message:
        type: "string"
  Conversation:
    type: "object"
    required:
    - "partner"
    properties:
      partner:
        type: "string"
  ListOfMessages:
    type: "object"
    required:
    - "messages"
    properties:
      messages:
        type: "array"
        items:
          $ref: "#/definitions/Message"
  ListOfConversations:
    type: "object"
    required:
    - "conversations"
    properties:
      conversations:
        type: "array"
        items:
          $ref: "#/definitions/Conversation"
  User:
    type: "object"
    required:
    - "email"
    - "password"
    properties:
      email:
        type: "string"
      password:
        type: "string"
